<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <IsPackable>true</IsPackable>
        <RootNamespace>System.Text.Json.Serialization</RootNamespace>
        <PackageId>JsonDerivedTypeGenerator.Attributes</PackageId>
    </PropertyGroup>

    <PropertyGroup Label="Nuget">
        <Authors>Jakub Tokarczyk</Authors>
        <Description>Attributes for JsonDerivedTypeGenerator source generator</Description>
        <PackageTags>source-generator;roslyn;json</PackageTags>
        <Copyright>© 2026 Jakub Tokarczyk</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/SarcasticMoose/JsonDerivedTypeGenerator</RepositoryUrl>
    </PropertyGroup>

</Project>
