<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <IsPackable>false</IsPackable>
        <OutputType>exe</OutputType>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3" Version="3.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\JsonDerivedTypeGenerator\JsonDerivedTypeGenerator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\JsonDerivedTypeGenerator.Attributes\JsonDerivedTypeGenerator.Attributes.csproj" />
    </ItemGroup>

</Project>
